// Proupose: This file contains the provinces of Ecuador and their respective letter.
const provincesLetters = {
    A: "Azuay",
    B: "Bolívar",
    U: "Cañar",
    C: "Carchi",
    X: "Cotopaxi",
    H: "Chimborazo",
    O: "El Oro",
    E: "Emeraldas",
    W: "Galápagos",
    G: "Guayas",
    I: "Imbabua",
    L: "Loja",
    R: "Los Ríos",
    M: "Manabí",
    V: "Morona Santiago",
    N: "Napo",
    S: "Pastaza",
    P: "Pichincha",
    Q: "Orellana",
    K: "Sucumbíos",
    T: "Tungurahua",
    Z: "Zamora Chinchipe",
    Y: "Santa Elena",
    J: "Santo Domingo de los Tsáchilas",
};
export default provincesLetters;
